### ISSUE TITLE
Feathers Plus

### ISSUE THREAD

**Issue by nmpribeiro** [BenZed/feathers-attribute-permissions#2]
Hi!

Any idea on showing docs on how to implement this with Feathers Plus? Could it work with Feathers Plus?

Thanks in advance

**Comment by BenZed** [comment]
In what way? I thought feathers plus was just a repository that is a collection of other useful repositories, no?

**Comment by nmpribeiro** [comment]
I see, it seems I was confused with the whole naming and documentation.

@BenZed so perhaps if I could have some information or documentation on how to implement feathers attribute permissions on Buzz would be super :smile: 

Actually, the reason I thought FeatherJS Plus was actually a new feathers version, was because I couldn't import this module as it sates in the README. After install and import, this is the output or `yarn start`:

```
➜ yarn start
yarn run v1.15.2
$ ts-node --files src/
Error: Cannot find module 'babel-runtime/regenerator'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/unitelabs/working/nr_web/react-feathers/server/node_modules/feathers-attribute-permissions/lib/permissions.js:7:20)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by nmpribeiro** [comment]
installing `yarn add babel-runtime@5.3.0` then gives
```
➜ yarn start
yarn run v1.15.2
$ ts-node --files src/
Error: Cannot find module 'babel-runtime/helpers/asyncToGenerator'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/[user]/working/nr_web/react-feathers/server/node_modules/feathers-attribute-permissions/lib/permissions.js:11:26)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜ yarn start
yarn run v1.15.2
$ ts-node --files src/
Error: Cannot find module 'babel-runtime/helpers/asyncToGenerator'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/[user]/working/nr_web/react-feathers/server/node_modules/feathers-attribute-permissions/lib/permissions.js:11:26)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nmpribeiro** [comment]
Only after installing `babel-runtime 7.0.0-beta.3`: `"babel-runtime": "7.0.0-beta.55",` in my `package.json` was I able to get your `feathers-attribute-permissions` import to work.

Guess I figured it out :+1:
